import assert from 'node:assert/strict';import {defaults,costFields,calculate,validateCosts} from './dist/calc.mjs';import {models} from './dist/models.mjs';import {callTool,toolDefinitions} from './src/mcp.mjs';
let n=0;const eq=(a,b)=>{assert.deepEqual(a,b);n++};const near=(a,b)=>{assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);n++};const ok=x=>{assert.ok(x);n++};const m={...models[0],success:80},s={...defaults};const zeros=Object.fromEntries(costFields.map(([k])=>[k,0]));
const old=calculate(s,m);eq(old.costs.complete,false);eq(old.costs.missing_cost_fields.length,12);eq(old.costs.full_monthly_usd,null);near(old.costs.known_monthly_usd,old.workflowMonthly);
const zero=calculate(s,m,zeros);eq(zero.costs.complete,true);eq(zero.costs.missing_cost_fields.length,0);near(zero.costs.full_monthly_usd,zero.workflowMonthly);near(zero.costs.fully_loaded_cost_per_resolved_task_usd,zero.costPerSuccess);
const costs={...zeros,setupParsing:100,setupEmbeddings:200,setupIndexing:300,amortizationMonths:6,allocatedSharePercent:25,queryEmbeddings:.002,retrieval:.003,reranking:.004,dataTransfer:.001,otherUsage:.01,vectorStorage:100,compute:200,monitoring:50,maintenance:50};
const r=calculate(s,m,costs);near(r.costs.setup_monthly_allocated,25);near(r.costs.fixed_monthly_allocated,100);near(r.costs.variable_per_attempt,.02);near(r.costs.variable_monthly,240);near(r.costs.known_monthly_usd,r.workflowMonthly+365);near(r.costs.known_cost_per_resolved_task_usd,r.costs.known_monthly_usd/r.successes);
for(const success of [0,20,80,100])for(const retries of [0,1,3]){const z=calculate({...s,retries},{...m,success},costs);near(z.costs.variable_monthly,.02*z.attempts*s.volume);near(z.costs.setup_monthly_allocated,25);near(z.costs.fixed_monthly_allocated,100);}
const empty=calculate({...s,volume:0},m,costs);near(empty.costs.known_monthly_usd,125);eq(empty.costs.known_cost_per_task_usd,null);eq(empty.costs.known_cost_per_resolved_task_usd,null);eq(empty.costs.fully_loaded_cost_per_resolved_task_usd,null);
const failed=calculate({...s,escalate:0},{...m,success:0},costs);eq(failed.costs.known_cost_per_resolved_task_usd,null);ok(failed.costs.known_monthly_usd>125);
near(calculate(s,m,{...costs,allocatedSharePercent:0}).costs.known_monthly_usd,r.workflowMonthly+240);near(calculate(s,m,{...costs,allocatedSharePercent:100}).costs.known_monthly_usd,r.workflowMonthly+240+500);
eq(calculate(s,m,{...zeros,vectorStorage:null}).costs.complete,false);eq(calculate(s,m,{vectorStorage:0}).costs.missing_cost_fields.length,11);
for(const bad of [{compute:-1},{compute:Infinity},{compute:NaN},{compute:'4'},{allocatedSharePercent:101},{amortizationMonths:0},{amortizationMonths:1.5},{secret:'x'},null])ok(validateCosts(bad).length>0);
const args={models:[{model_id:m.id,success_percent:80}],workload:s,additional_costs:costs};const viaMcp=callTool('estimate_workflow_cost',args);eq(viaMcp.structuredContent.results[0].costs,r.costs);eq(viaMcp.structuredContent.completeness.status,'entered_scope_complete');
const legacy=callTool('estimate_workflow_cost',{models:args.models,workload:s});eq(legacy.structuredContent.completeness.status,'partial_missing_costs');ok(legacy.summary.includes('PARTIAL'));near(legacy.structuredContent.results[0].workflowMonthly,old.workflowMonthly);eq(toolDefinitions.find(t=>t.name==='estimate_workflow_cost').inputSchema.required,['models','workload']);
console.log(`${n} additional-cost arithmetic/completeness/MCP-parity assertions passed`);
