import {defaults,limits,validate,calculate,costFields,validateCosts} from '../dist/calc.mjs';
import {models,checked} from '../dist/models.mjs';
import {workflows,workflowTotals,applyWorkflow} from '../dist/workflows.mjs';
import {infraScenarios,infraFields,infrastructureScenario} from '../dist/infrastructure.mjs';
const object=properties=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const descriptions={input:'Total input tokens per call, averaged across calls; includes cached input',cached:'Eligible cache-read tokens per call, subset of input; excludes cache creation/storage',output:'Billable output tokens per call, averaged across calls; include billed reasoning',calls:'Number of model calls in one complete task attempt',volume:'Business tasks per month',retries:'Maximum retries after the first complete attempt; retry the full sequence on failure',toolCalls:'Expected separately charged tool calls per complete attempt',toolCost:'USD per separately charged tool call',escalate:'Percent of tasks still unresolved after all attempts sent to a human',humanCost:'USD per human escalation, paid whether successful or not',humanSuccess:'Percent of escalations the human resolves'};
const numeric=(key)=>({description:descriptions[key],type:['input','cached','output','calls','volume','retries'].includes(key)?'integer':'number',minimum:limits[key][0],maximum:limits[key][1]});
const apiKeys=['input','cached','output','calls','volume'];
const modelId={type:'string',enum:models.map(m=>m.id)};
const selection={type:'array',minItems:1,maxItems:3,uniqueItems:true,items:modelId};
const metadataDescription='USD standard text-token subtotal. Prices are a dated snapshot, not live. Inputs are assumptions, not measured success or quality. No external model calls or billing access.';
const annotations={readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false};
export const toolDefinitions=[
{name:'compare_model_api_costs',title:'Compare model API costs',description:'Compare 1–3 curated text models using identical numeric workloads. input/output/cached are per-call tokens; cached is a subset of input. calls is calls per task attempt and volume is monthly tasks. One attempt only. '+metadataDescription,inputSchema:object({model_ids:selection,workload:object(Object.fromEntries(apiKeys.map(k=>[k,numeric(k)])))}),annotations},
{name:'estimate_workflow_cost',title:'Estimate workflow cost per resolution',description:'Calculate expected total and cost per resolved task with capped retries, tool fees and human escalation. Supply every numeric assumption explicitly. Success rates describe the complete attempt, are user assumptions and must never be inferred from model prices. All calls in an attempt use the same model; retries repeat the full attempt. '+metadataDescription,inputSchema:object({models:{type:'array',minItems:1,maxItems:3,items:object({model_id:modelId,success_percent:{type:'number',minimum:0,maximum:100}})},workload:object(Object.fromEntries(Object.keys(limits).map(k=>[k,numeric(k)])))}),annotations},
{name:'get_workflow_examples',title:'Get illustrative workflow examples',description:'Read synthetic support, summary, invoice-extraction and account-brief examples with per-step token breakdowns and exact per-call normalization. No customer text, secrets, model quality measurements or live usage.',inputSchema:{type:'object',properties:{example_id:{type:'string',enum:workflows.map(p=>p.id)}},additionalProperties:false},annotations}
];
toolDefinitions.push({name:'get_infrastructure_scenarios',title:'Explore illustrative infrastructure costs',description:'Get three editable examples using sourced OpenAI embedding and Railway resource rates. Sizes and maintenance labour are hypothetical, not capacity benchmarks. Numeric overrides let you explore assumptions. Returns exact cost mapping for estimate_workflow_cost when can_load is true; unknown fields are omitted so the returned additional_costs can be passed directly. Always preserve partial-cost warnings and distinguish complete attempts from task volume.',inputSchema:{type:'object',properties:{scenario_id:{type:'string',enum:infraScenarios.map(p=>p.id)},overrides:{type:'object',properties:Object.fromEntries(infraFields.map(([k,label,max])=>[k,{type:'number',minimum:0,maximum:max,description:label}])),additionalProperties:false}},additionalProperties:false},annotations});
const costSchema={type:'object',properties:Object.fromEntries([...costFields.map(([k,label])=>[k,{type:'number',minimum:0,maximum:1e9,description:label+' in USD. Omit if unknown; use 0 only if reviewed and not applicable or already counted elsewhere.'}]),['amortizationMonths',{type:'integer',minimum:1,maximum:1200,description:'Months to spread setup costs over, default12; does not imply billing schedule'}],['allocatedSharePercent',{type:'number',minimum:0,maximum:100,description:'Share of setup and fixed budgets allocated to this workload, default100'}]]),additionalProperties:false};
const workflowTool=toolDefinitions.find(t=>t.name==='estimate_workflow_cost');workflowTool.inputSchema.properties.additional_costs=costSchema;workflowTool.description+=' Optional additional_costs covers setup, usage and shared monthly infrastructure. Omitted fields mean unknown, not zero. Results remain partial until every cost category is supplied or explicitly0.';
function check(value,schema){if(schema.type==='object'){if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Expected an object');for(const k of Object.keys(value))if(!Object.hasOwn(schema.properties,k))throw Error('Unexpected argument');for(const k of schema.required??[])if(!Object.hasOwn(value,k))throw Error('Missing required argument');for(const k of Object.keys(value))check(value[k],schema.properties[k]);}else if(schema.type==='array'){if(!Array.isArray(value)||value.length<schema.minItems||value.length>schema.maxItems)throw Error('Invalid selection length');if(schema.uniqueItems&&new Set(value).size!==value.length)throw Error('Duplicate selection');value.forEach(v=>check(v,schema.items));}else if(schema.type==='string'){if(typeof value!=='string'||(schema.enum&&!schema.enum.includes(value)))throw Error('Unknown identifier');}else if(typeof value!=='number'||!Number.isFinite(value)||value<schema.minimum||value>schema.maximum||(schema.type==='integer'&&!Number.isInteger(value)))throw Error('Invalid numeric assumption');}
const exclusions=['Cache-write and explicit-cache storage fees unless manually included in additional costs','Long-context and regional premiums','Taxes, currency conversion, batch/flex/priority/contract discounts','OCR/file parsing unless entered as setup or usage; image/audio model billing is not modelled','Provider tool charges unless explicitly included in workflow toolCost or additional costs','Unentered business costs, latency and correlated failures'];
function metadata(selected,workload){const warnings=[];if(workload?.cached>0)warnings.push('Warm-cache read subtotal; cache writes and storage are excluded. Cache-hit eligibility is not guaranteed.');if(workload?.input>272000&&selected.some(m=>m.id.startsWith('gpt-')))warnings.push('OpenAI base tier exceeded; subtotal excludes required long-context premium. Do not use as a final quote.');if(workload?.input+workload?.output>200000&&selected.some(m=>m.id.startsWith('claude-haiku')))warnings.push('Workload exceeds Haiku context limit.');if(workload?.input>1048576||workload?.output>65536)warnings.push('Check per-model context and output limits; this workload may not be supported.');if(selected.some(m=>m.id==='gemini-3.8-flash'))warnings.push('Gemini 3.8 Flash preset uses promotional rates ending 2026-12-31; from 2027-01-01 update rates before relying on this subtotal.');return {currency:'USD',price_checked_utc:checked,rate_basis:'USD per 1 million tokens; standard global text API snapshot',input_confidence:'User-provided assumptions; not independently measured or verified',exclusions,warnings,sources:selected.map(m=>({model_id:m.id,name:m.name,input_rate:m.input,output_rate:m.output,cache_read_rate:m.cached,source_url:m.url,rate_notes:m.note}))};}
export function callTool(name,args){const def=toolDefinitions.find(t=>t.name===name);if(!def)throw Error('Unknown tool');check(args,def.inputSchema);if(name==='get_infrastructure_scenarios'){if(args.overrides&&!args.scenario_id)throw Error('Choose a scenario_id when using overrides');const examples=(args.scenario_id?[args.scenario_id]:infraScenarios.map(p=>p.id)).map(id=>infrastructureScenario(id,args.overrides??{}));return {summary:'Illustrative infrastructure and embedding budgets, not all-in quotes or capacity benchmarks. Unknown parsing/indexing and stated exclusions keep these partial. Source prices checked2026-10-01; sizing and labour assumptions are editable.',structuredContent:{kind:'infrastructure_scenarios',scenarios:examples}};}if(name==='get_workflow_examples'){const found=args.example_id?workflows.filter(p=>p.id===args.example_id):workflows;return {summary:`${found.length} illustrative workflow example(s). Synthetic budgets, not measured usage.`,structuredContent:{kind:'illustrative_examples',confidence:'Synthetic teaching examples, not measured token usage or quality',examples:found.map(p=>({...p,totals:workflowTotals(p),calculator_token_inputs:{input:workflowTotals(p).averageInput,output:workflowTotals(p).averageOutput,calls:p.steps.length,cached:0},normalization:'Average tokens per call × calls recovers exact task-attempt totals. A retry repeats the whole sequence. Shared model and rates across calls.'})),pricing_metadata:metadata([],null)}};}
const workflow=name==='estimate_workflow_cost';const entries=workflow?args.models:args.model_ids.map(model_id=>({model_id,success_percent:80}));if(new Set(entries.map(e=>e.model_id)).size!==entries.length)throw Error('Duplicate model');const chosen=entries.map(e=>({...models.find(m=>m.id===e.model_id),success:e.success_percent}));const state=workflow?args.workload:{...defaults,...args.workload};if(validate(state,chosen).length)throw Error('Inconsistent numeric assumptions: cached input cannot exceed total input');const costErrors=validateCosts(args.additional_costs);if(costErrors.length)throw Error(costErrors.join("; "));const results=chosen.map(m=>{const r=calculate(state,m,args.additional_costs);return workflow?{model_id:m.id,...r}:{model_id:m.id,per_call_usd:r.perCall,per_task_usd:r.perAttempt,monthly_api_subtotal_usd:r.apiMonthly};});const details={kind:workflow?'workflow_estimate':'api_comparison',...metadata(chosen,state),assumptions:args,results};if(workflow){details.completeness={status:results.every(r=>r.costs.complete)?'entered_scope_complete':'partial_missing_costs',missing_cost_fields:results[0].costs.missing_cost_fields,legacy_fields:'total, workflowMonthly and costPerSuccess remain model+tools+human subtotals for compatibility; use costs.known_monthly_usd and costs.known_cost_per_resolved_task_usd for entered overhead',disclaimer:'Complete means all cost categories reviewed, not a guarantee of all-in cost. Unknown costs are excluded from known subtotal, not assumed zero.'};details.workflow_rules=['Success is per complete attempt, not per call','Independent constant-cost attempts stop at first success; max attempts = retries + 1','Only remaining failures can escalate; human and AI resolutions do not overlap','All failed work is included in cost per final resolution; zero volume or zero success yields null'];details.result_units='Cost fields are USD; probability fields are fractions from 0 to 1; attempts and successes are expected counts.';}
return {summary:workflow?`${results.every(r=>r.costs.complete)?'Entered-scope workflow estimates':'PARTIAL workflow estimates: some operating costs are not provided'} for ${chosen.length} model(s). Includes failed work, configured tool fees, human escalations and known additional costs. Blank costs are unknown, not zero. Success rates are user assumptions, not benchmarks.`:`API token subtotals for ${chosen.length} model(s) at ${state.volume} tasks/month. One attempt only; retries, tools and human work excluded.`,structuredContent:details};}
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
const rpcError=(id,code,message,status=200)=>json({jsonrpc:'2.0',id,error:{code,message}},status);
export async function handleMcp(request,{authenticated=false}={}){if(request.method!=='POST')return new Response('Use POST for stateless MCP',{status:405,headers:{Allow:'POST'}});if(!request.headers.get('content-type')?.toLowerCase().startsWith('application/json'))return rpcError(null,-32600,'Expected application/json',415);let message;try{const reader=request.body?.getReader();if(!reader)return rpcError(null,-32700,'Missing JSON body',400);let size=0,parts=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>65536){await reader.cancel();return rpcError(null,-32600,'Request too large',413);}parts.push(value);}const buffer=new Uint8Array(size);let pos=0;for(const part of parts){buffer.set(part,pos);pos+=part.length;}message=JSON.parse(new TextDecoder().decode(buffer));}catch{return rpcError(null,-32700,'Invalid JSON',400);}
if(!message||Array.isArray(message)||message.jsonrpc!=='2.0'||typeof message.method!=='string'||(Object.hasOwn(message,'id')&&typeof message.id!=='string'&&!(typeof message.id==='number'&&Number.isFinite(message.id))))return rpcError(null,-32600,'Invalid JSON-RPC request',400);
const {id,method,params}=message;if(!Object.hasOwn(message,'id'))return new Response(null,{status:202});
if(method==='initialize'){if(!params||typeof params.protocolVersion!=='string')return rpcError(id,-32602,'Missing protocolVersion');const protocolVersion=['2024-11-05','2025-03-26','2025-06-18'].includes(params.protocolVersion)?params.protocolVersion:'2025-06-18';return json({jsonrpc:'2.0',id,result:{protocolVersion,capabilities:{tools:{listChanged:false}},serverInfo:{name:'ai-cost-lab',version:'1.0.0'},instructions:'Read-only numerical estimates. Use explicit user assumptions. Never infer model success rates from pricing. Keep customer text and credentials out of inputs.'}});}
if(method==='ping')return json({jsonrpc:'2.0',id,result:{}});
if(method==='tools/list')return json({jsonrpc:'2.0',id,result:{tools:toolDefinitions}});
if(method!=='tools/call')return rpcError(id,-32601,'Method not found');
// Authentication is established by the hosting adapter, never by client identity headers.
if(authenticated!==true)return rpcError(id,-32001,'Authenticated user required',401);
if(!params||typeof params!=='object'||Array.isArray(params)||typeof params.name!=='string'||Object.keys(params).some(k=>!['name','arguments','_meta'].includes(k)))return rpcError(id,-32602,'Invalid tool-call parameters');
try{const output=callTool(params.name,params.arguments===undefined?{}:params.arguments);return json({jsonrpc:'2.0',id,result:{content:[{type:'text',text:output.summary+'\n'+(output.structuredContent.results??[]).map(r=>r.model_id+': '+(r.monthly_api_subtotal_usd!==undefined?'monthly API subtotal USD '+r.monthly_api_subtotal_usd.toFixed(4):(r.costs.complete?'entered-scope monthly total USD ':'PARTIAL known monthly subtotal USD ')+r.costs.known_monthly_usd.toFixed(4)+'; '+(r.costs.complete?'fully loaded within entered scope':'PARTIAL known cost')+' per resolved task '+(r.costs.known_cost_per_resolved_task_usd===null?'not defined (zero volume or zero success)':'USD '+r.costs.known_cost_per_resolved_task_usd.toFixed(4)))).join('\n')+'\n'+JSON.stringify(output.structuredContent)}],structuredContent:output.structuredContent,isError:false}});}catch(e){return json({jsonrpc:'2.0',id,result:{content:[{type:'text',text:e.message}],isError:true}});}}
